services:
  - type: web
    name: weather-predictor
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install --only-binary :all: numpy
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PYTHONPATH
        value: . 