services:
  - type: web
    name: weather-predictor
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: PYTHONPATH
        value: .
    plan: standard 