services:
  - type: web
    name: weather-predictor
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONPATH
        value: . 